const projects = [
  {
    id: 'proj_001',
    title: 'Full-Stack E-Commerce App',
    description: 'Complete shopping platform with cart, payments, admin dashboard, and order tracking.',
    tech: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    price: 499,
    demoUrl: 'https://your-demo-link.com/ecommerce',
    thumbnail: 'https://placehold.co/600x340/6366f1/white?text=E-Commerce+App',
    features: ['User Auth', 'Product Management', 'Cart & Checkout', 'Admin Panel', 'Order History'],
  },
  {
    id: 'proj_002',
    title: 'Real-Time Chat Application',
    description: 'WhatsApp-style chat app with rooms, private messaging, and online status.',
    tech: ['React', 'Socket.io', 'Node.js', 'MongoDB'],
    price: 349,
    demoUrl: 'https://your-demo-link.com/chat',
    thumbnail: 'https://placehold.co/600x340/10b981/white?text=Chat+App',
    features: ['Real-time Messaging', 'Chat Rooms', 'Private DMs', 'Online Status', 'File Sharing'],
  },
  {
    id: 'proj_003',
    title: 'Developer Portfolio Website',
    description: 'Clean, responsive portfolio with animations, project showcase, and contact form.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    price: 149,
    demoUrl: 'https://your-demo-link.com/portfolio',
    thumbnail: 'https://placehold.co/600x340/f59e0b/white?text=Portfolio+Website',
    features: ['Responsive Design', 'Smooth Animations', 'Project Gallery', 'Contact Form', 'Dark Mode'],
  },
  {
    id: 'proj_004',
    title: 'Task Management App',
    description: 'Trello-like kanban board with drag & drop, deadlines, and team collaboration.',
    tech: ['Vue.js', 'Firebase', 'Tailwind CSS'],
    price: 399,
    demoUrl: 'https://your-demo-link.com/taskmanager',
    thumbnail: 'https://placehold.co/600x340/ef4444/white?text=Task+Manager',
    features: ['Kanban Board', 'Drag & Drop', 'Team Sharing', 'Deadlines', 'Notifications'],
  },
  {
    id: 'proj_005',
    title: 'Blog CMS Platform',
    description: 'Full-featured blog with markdown editor, categories, comments, and SEO.',
    tech: ['Next.js', 'PostgreSQL', 'Prisma'],
    price: 449,
    demoUrl: 'https://your-demo-link.com/blog',
    thumbnail: 'https://placehold.co/600x340/8b5cf6/white?text=Blog+CMS',
    features: ['Markdown Editor', 'Categories & Tags', 'Comments', 'SEO Optimized', 'RSS Feed'],
  },
  {
    id: 'proj_006',
    title: 'Expense Tracker App',
    description: 'Personal finance tracker with charts, budgets, and monthly reports.',
    tech: ['React', 'Chart.js', 'LocalStorage'],
    price: 199,
    demoUrl: 'https://your-demo-link.com/expense',
    thumbnail: 'https://placehold.co/600x340/06b6d4/white?text=Expense+Tracker',
    features: ['Income & Expense Tracking', 'Charts & Graphs', 'Budget Limits', 'Monthly Reports', 'Export CSV'],
  },
];
